// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// import { AuthProvider } from "../context/AuthContext";
// import { AdminProvider } from "../context/adminContext";
// import { BusOperatorProvider } from "../context/BusOperatorContext";
// import { AgentProvider } from "../context/AgentContext";
// import { HotelOwnerProvider } from "../context/HotelOwnerContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <AuthProvider>
//       <AdminProvider>
//         <BusOperatorProvider>
//           <AgentProvider>
//             <HotelOwnerProvider>
//               <html lang="en">
//                 <body
//                   className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//                 >
//                   {children}
//                 </body>
//               </html>
//             </HotelOwnerProvider>
//           </AgentProvider>
//         </BusOperatorProvider>
//       </AdminProvider>
//     </AuthProvider>
//   );
// }



// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// import { AuthProvider } from "../context/AuthContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <AuthProvider>
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//     </AuthProvider>
//   );
// }


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "../context/AuthContext";
import { HotelOwnerProvider } from "../context/HotelOwnerContext"; // 
import { BusOperatorProvider } from "@/context/BusOperatorContext";
import { AdminProvider } from "@/context/adminContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <BusOperatorProvider>
      <HotelOwnerProvider> {/* ✅ wrap here */}
        <AdminProvider>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            {children}
          </body>
        </html>
        </AdminProvider>
      </HotelOwnerProvider>
      </BusOperatorProvider>
    </AuthProvider>
  );
}

